server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**
            - After=2020-10-01T08:02:32.223+08:00[Asia/Shanghai]

        - id: payment_routh2
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
              - Path=/payment/lb/**

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true  #表示是否将自己注册进EurekaServer，默认为true
    fetch-registry: true        #是否从eurekaServer抓去已有的注册信息，集群必须设置为true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
