server:
  port: 8006
spring:
  application:
    name: cloud-provide-payment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://118.31.103.39:3306/Ken_demo
    username: root
    password: 123456
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
      discovery:
        service-name: ${spring.application.name}