server:
  port: 8001


spring:
  application:
    name: cloud-payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://118.31.103.39:3306/Ken_demo
    username: root
    password: 123456

eureka:
  client:
    register-with-eureka: true  #表示是否将自己注册进EurekaServer，默认为true
    fetch-registry: true        #是否从eurekaServer抓去已有的注册信息，集群必须设置为true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001      #微服务信息完善，更改主机名称
    prefer-ip-address: true       #访问路径可以显示IP地址
    lease-expiration-duration-in-seconds: 2   #服务端在收到最后一次心跳后等待时间上限，默认为90s，超时将剔除服务
    lease-renewal-interval-in-seconds: 1      #客户端向服务端发送心跳的时间间隔


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities    # 所有Entity别名类所在包