server:
  port: 80

spring:
  application:
    name: cloud-order-feign-hystrix

eureka:
  client:
    register-with-eureka: true  #表示是否将自己注册进EurekaServer，默认为true
    fetch-registry: true        #是否从eurekaServer抓去已有的注册信息，集群必须设置为true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 5000



